name: Build dylib

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build KeychainWipe.dylib
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          clang -arch arm64 \
                -isysroot "$SDK" \
                -framework Foundation \
                -framework Security \
                -dynamiclib \
                -install_name @rpath/KeychainWipe.dylib \
                -o KeychainWipe.dylib \
                KeychainWipe.m

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: KeychainWipe-dylib
          path: KeychainWipe.dylib
